language: rust
sudo: false

cache:
  - cargo

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/cargo-readme || cargo install --vers "^3" cargo-readme)
  - cargo install-update -a

matrix:
  include:
    - rust: stable
      env: JOB=stable-tests
      script:
        - cargo test
        - cargo test --features serde
    - rust: beta
      env: JOB=beta-tests
      script:
        - cargo test
        - cargo test --features serde
    - rust: nightly
      env: JOB=nightly-tests
      script:
        - cargo test
        - cargo test --features serde
        - cargo test --no-default-features
        - cargo test --no-default-features --features serde
